### ISSUE TITLE
Should this repo be public or private

### ISSUE THREAD

**Issue by okwme** [allinbits/burner-chains#15]
I like the idea that it can be public, and if it can i think it should. But if we decide to use it for internal marketing topics like mentioned in #14 it might be good to make it private.

Thoughts?

**Comment by tac0turtle** [comment]
I am for keeping it public. As you can see external people have already stared it. I don't think there would any private information be divulged here so it's not a worry at least to me.

**Comment by Michelle-L** [comment]
I think a private repo is the best starting point, and here's why: 

1. I think it gives us time to flesh out the idea, coordinate, communicate and strategize
2. It is more organized and complete when launched. This doesn't mean it can't have different versions or iterations once public

However, none of this makes sense if the whole point is to get community contributions to the burner chains right off the bat? Or we could have two one public and one private, we develop the private one in tandem to the more community contribution one and see how the two differ or don't?

**Comment by tac0turtle** [comment]
Think this was decided 😄. Stays public.
